apiVersion: v1

kind: Pod

metadata:
    name: myapp-pod
    labels:
        app: myapp
        type: front-end

specs: 
    containers:
        -name: ngnix-containers
         image: ngnix:1.2.3
         
command to create pod

kubectl create -f pod-definition.yml